### ISSUE TITLE
Getting the RSSI

### ISSUE THREAD

**Issue by rlsaurabh** [rksg/gpb_mqtt_sample_client#2]
This is a query.

Instead of getting the (x,y) , is there any way of getting the RSSI of the Wifi device on each AP?

Kindly let me know. Thanks!

**Comment by yeongsheng-tan** [comment]
Hi @rlsaurabh the API end-point as its name states, is purely for Location data streaming, meaning the end-point does 1 and only 1 thing, and that is to provide the calculated x, y and floor coordinates of a device MAC located at a specific venue.

If there is a requirement for providing raw APs RSSI for each device MAC, it would require subscribing to our Pre-Engine API published over MQTT, but packed in a different format. You may talk to our Sales or PLM team to request for such features. As for now, the Post-Engine (as the name states - it publishes locator engine calculated data) does not provide the raw pre-calculated data, and it would not befit the intent of a 'Post-Engine' API.

Hope the above clarifies.

**Comment by rlsaurabh** [comment]
Thanks for the info.
