### ISSUE TITLE
Casing error in topic in README.md

### ISSUE THREAD

**Issue by rwuttke** [rksg/gpb_mqtt_sample_client#3]
The example to run mosquitto_sub has a casing error in the topic, it currently reads

`mosquitto_sub -p 1883 -t "1.0.0/LOC/SPoT_GPB/#"`

I believe this should be

`mosquitto_sub -p 1883 -t "1.0.0/LOC/SPOT_GPB/#"`

**Comment by yeongsheng-tan** [comment]
@rwuttke I've updated the main page README.md and https://github.com/rksg/gpb_mqtt_sample_client/blob/master/mqtt_bridge_conf/mosquitto_bridge.conf.sample to reflect the correct settings.

I've also added additional hints to setting up the PSK and PSK-Identity in the file https://github.com/rksg/gpb_mqtt_sample_client/blob/master/mqtt_bridge_conf/mosquitto_bridge.conf.sample in README.md.

Kindly review and let us know if we could spruce it up some more to make it more helpful.

**Comment by rwuttke** [comment]
@yeongsheng-tan I've had a look at your additional changes.

The extra hints, 
1. the website to do the conversion is very much appreciated
2. the clearer spelling out of the topics is definitely **clearer**

**Comment by yeongsheng-tan** [comment]
@rwuttke thank you for the prompt feedback.
